version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: mkdir junit
      - store_test_results:
          path: junit
      - run: npm install
      - run: npm install rimraf -g
      - run: npm install babel-tape-runner -g
      - run: npm run test-ci --silent >./junit/tape.xml
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: sudo apt-get install ruby ruby-dev gcc make icnsutils graphicsmagick xz-utils
      - run: gem install fpm
      - run: npm install
      - run: npm run dist
workflows:
  test-n-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
